AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Sharp Lambda Layer

  A lambda layer containing the Sharp library for nodejs

  '
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sharp-lambda-layer
      Description: A lambda layer containing the Sharp library for nodejs
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-19sa888th0zo6/sharp-lambda-layer/dc7eb3789547f2849aae37a2badac897
      CompatibleRuntimes:
      - nodejs12.x
      - nodejs14.x
Outputs:
  LayerArn:
    Value:
      Ref: SharedLayer
Metadata:
  AWS::ServerlessRepo::Application:
    Name: nodejs-sharp-lambda-layer
    Description: 'Lambda-compatible build of the nodejs Sharp library

      '
    Author: Paul Spencer
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-19sa888th0zo6/sharp-lambda-layer/19cbd64715b51267a47bf3750cc6a8a5
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-19sa888th0zo6/sharp-lambda-layer/4d426ea1d44d09acc5d0f68186ebeafe
    Labels:
    - layer
    - image
    - lambda
    - sharp
    SemanticVersion: '0.0.1'
